import Checkbox from "@/componets/about/Checkbox";
import { ABOUT_TEXT, ABOUT_TEXT_SECOND } from "@/constants/modals";
import WrapperBackground from "@/componets/common/wrappers/WrapperBakground";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import Head from "next/head";
import React, { useState } from "react";
import HeaderModal from "@/componets/common/headerModal/HeaderModal";
import PrimarySubmitBtn from "@/componets/common/buttons/PrimarySubmitBtn";
import { userSlice } from "@/store/reducers/userSlice";
import { useAppDispatch } from "@/hooks/reducers.hook";
import { useRouter } from "next/router";
import { APP_ROUTES } from "@/constants/common";
import localStorageHandler from "@/utils/local-storage-hendler";

const SignIn: React.FC = () => {
  const [checked, setChecked] = useState<boolean>(false);
  console.log("checked", checked);
  const { setReadAbout } = userSlice.actions;
  const dispatch = useAppDispatch();
  const router = useRouter();

  const continueClickHandler = () => {
    console.log("click continue", "checked", checked);
    if (checked) {
      console.log("is checked");
      dispatch(setReadAbout());
      localStorageHandler.setIsReadAbout();
      router.push(APP_ROUTES.Details);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal
          width={"721"}
          header={"About the platform"}
          text={ABOUT_TEXT}
          textSecond={ABOUT_TEXT_SECOND}
        >
          <Checkbox
            label={"I have read the above statement"}
            checked={checked}
            setChecked={setChecked}
          />
          <PrimarySubmitBtn
            label={"continue"}
            clickHandler={continueClickHandler}
          />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignIn;
