import Checkbox from "@/componets/about/Checkbox";
import { ABOUT_TEXT, ABOUT_TEXT_SECOND } from "@/constants/modals";
import WrapperBackground from "@/componets/common/wrappers/WrapperBakground";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import Head from "next/head";
import React, { useState } from "react";
import HeaderModal from "@/componets/common/headerModal/HeaderModal";
import PrimarySubmitBtn from "@/componets/common/buttons/PrimarySubmitBtn";
import { userSlice } from "@/store/reducers/userSlice";
import { useAppDispatch } from "@/hooks/reducers.hook";
import { useRouter } from "next/router";
import { APP_ROUTES, StorageCellEnum } from "@/constants/common";
import localStorageHandler from "@/utils/local-storage-hendler";
import userService from "@/api/user-service";
import { useEffect } from "react";
import { ILocalStorageData } from "../../../types/common.types";

const SignIn: React.FC = () => {
  const [checked, setChecked] = useState<boolean>(false);
  console.log("checked", checked);
  const { setReadAbout } = userSlice.actions;
  const dispatch = useAppDispatch();
  const router = useRouter();
  const { signin } = userSlice.actions;

  useEffect(() => {
    let localData = localStorage.getItem(StorageCellEnum.USER);
    if (localData) {
      const parsedData: ILocalStorageData = JSON.parse(localData);
      dispatch(
        signin({
          id: parsedData.id,
          email: parsedData.email,
          name: parsedData.name!,
          phone: parsedData.phone!,
          nextPayment: parsedData.nextpayment as string,
          questionsAmount: parsedData.questionsamount,
          readAbout: parsedData.readabout,
          shareLink: !!parsedData.shareLink,
        })
      );
    }
  }, []);

  const continueClickHandler = async () => {
    console.log("click continue", "checked", checked);
    if (checked) {
      console.log("is checked");
      dispatch(setReadAbout());
      localStorageHandler.setIsReadAbout();
      try {
        const response = await userService.about();
        console.log("write type about", response);
        if (response.status === 200) {
          router.push(APP_ROUTES.Details);
        } else {
          alert("Error: newtwork error! Try again");
        }
      } catch (err) {
        console.error("Error", err);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal
          width={"721"}
          header={"About the platform"}
          text={ABOUT_TEXT}
          textSecond={ABOUT_TEXT_SECOND}
          minHeight={519}
          maxHeight={526}
        >
          <Checkbox
            label={"I have read the above statement"}
            checked={checked}
            setChecked={setChecked}
          />
          <PrimarySubmitBtn
            label={"continue"}
            clickHandler={continueClickHandler}
          />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignIn;
