import BackgroundDetails from "@/componets/details/BackgroundDetails";
import DetailsForm from "@/componets/details/DetailsForm";
import UpdatePaymentBlock from "@/componets/details/UpdatePaymentBlock";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styled from "styled-components";
import Header from "@/componets/common/header/Header";
import Footer from "@/componets/common/footer/Footer";
import { StyledContent } from "../index";
import { useAppDispatch, useAppSelector } from "@/hooks/reducers.hook";
import localStorageHandler from "@/utils/local-storage-hendler";
import { userSlice } from "@/store/reducers/userSlice";
import { StorageCellEnum } from "@/constants/common";
import { ILocalStorageData } from "../../../types/common.types";

const Details: React.FC = () => {
  const { signin } = userSlice.actions;
  const dispatch = useAppDispatch();

  useEffect(() => {
    let localData = localStorage.getItem(StorageCellEnum.USER);
    if (localData) {
      const parsedData: ILocalStorageData = JSON.parse(localData);
      dispatch(
        signin({
          id: parsedData.id,
          email: parsedData.email,
          name: parsedData.name!,
          phone: parsedData.phone!,
          nextPayment: parsedData.nextpayment as string,
          questionsAmount: parsedData.questionsamount,
          readAbout: parsedData.readabout,
          shareLink: !!parsedData.shareLink,
        })
      );
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperDetailsCentring>
        <StyledDetailsContent>
          <StyledHeaderContainer>
            <Header />
          </StyledHeaderContainer>
          <StyledModalWrapper>
            <WrapperModal
              width={"760"}
              isPaddingSmall={true}
              minHeight={594}
              maxHeight={742}
            >
              <WrapperDetailsForm>
                <p>Account Details</p>
                <DetailsForm />
              </WrapperDetailsForm>
            </WrapperModal>
            <WrapperModal
              width={"760"}
              isPaddingSmall={true}
              minHeight={328}
              maxHeight={365}
            >
              <UpdatePaymentBlock />
            </WrapperModal>
          </StyledModalWrapper>

          <StyledFooterContainer>
            <Footer />
          </StyledFooterContainer>
        </StyledDetailsContent>
        <BackgroundDetails />
      </WrapperDetailsCentring>
    </>
  );
};

const StyledDetailsContent = styled(StyledContent)`
  height: 100%;
  min-height: 1543px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const WrapperDetailsCentring = styled.div`
  width: 100%;
  height: 1543px;
  min-height: 1543px;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  background: transparent;
  overflow-x: hidden;
  overflow-y: auto;

  @media (max-width: 870px) {
    height: 800px;
    min-height: 800px;
  }
`;

const StyledHeaderContainer = styled.div`
  position: absolute;
  top: 0px;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`;

const StyledFooterContainer = styled.div`
  position: absolute;
  bottom: 0px;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`;

const StyledModalWrapper = styled.div`
  margin-bottom: 5.69vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  & > div:last-child {
    margin-top: 24px;
  }
`;
const WrapperDetailsForm = styled.div`
  margin-top: -2px;
  /* margin-left: -8px; */
  & > p {
    font-family: "Avenir Extra-bold";
    font-weight: 800;
    font-size: 24px;
    line-height: 150%;
    letter-spacing: -0.01em;
    color: white;
  }

  @media (max-width: 870px) {
    margin-top: 0px;
  }
`;

export default Details;
