import WrapperBackground from "@/componets/common/wrappers/WrapperBakground";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import Head from "next/head";
import React from "react";
import HeaderModal from "@/componets/common/headerModal/HeaderModal";
import NewPasswordForm from "@/componets/newPassword/NewPasswordForm";

const NewPassword: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal width={"721"} header={"Change Password"}>
          <NewPasswordForm />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default NewPassword;
