import SignInForm from "@/componets/signin/SignInForm";
import WrapperBackground from "@/componets/common/wrappers/WrapperBakground";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import Head from "next/head";
import React, { useEffect } from "react";
import AdditionalFormInfo from "@/componets/common/additionalFormInfo/AdditionalFormInfo";
import HeaderModal from "@/componets/common/headerModal/HeaderModal";
import { APP_ROUTES, StorageCellEnum } from "@/constants/common";
import { userSlice } from "@/store/reducers/userSlice";
import { useAppDispatch } from "@/hooks/reducers.hook";
import { ILocalStorageData } from "../../../types/common.types";

const SignIn: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal
          width={"721"}
          header={"Login"}
          minHeight={512}
          maxHeight={640}
        >
          <SignInForm />

          <AdditionalFormInfo
            label="Don’t have an account?"
            labelLink="Sign up"
            wayLink={APP_ROUTES.Signup}
          />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignIn;
