import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";
import Header from "@/componets/common/header/Header";
import SoulsModal from "@/componets/common/modals/soulModal/SoulsModal";
import MenuModal from "@/componets/common/modals/menuModal/MenuModal";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";
import Individual from "@/componets/chat/individual/Individual";
import Messages from "@/componets/chat/messages/Messages";
import { getIndividualDataForId } from "@/utils/functions";
import WrapperPage from "@/componets/common/wrappers/WrapperPage";

const Chat: React.FC = () => {
  const router = useRouter();
  const currentId = router.query.id as string;
  const currentIndividualData = getIndividualDataForId(currentId);
  console.log("individuals id:", router.query.id);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperPage color={"#0a0907"}>
        <StyledSectionWrapper>
          <Header />
          <StyledChatContainer>
            <div>
              <Individual individualData={currentIndividualData} />
            </div>
            <div>
              <Messages avatarImg={currentIndividualData?.image} />
            </div>
          </StyledChatContainer>
        </StyledSectionWrapper>
      </WrapperPage>
    </>
  );
};

const StyledSectionWrapper = styled.section`
  width: 100%;
  height: 100%;
  min-height: 100%;
  background-color: #0a0907;
  overflow: hidden;

  @media (min-width: 1600px) {
    min-height: 1405px;
  }

  @media (max-width: 1600px) {
    min-height: 100%;
  }

  @media (max-width: 1200px) {
    overflow-y: auto;
    min-height: 812px;
  }
`;

const StyledChatContainer = styled.main`
  position: relative;
  height: calc(100% - 96px);
  min-height: calc(100% - 96px);
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  background-color: #0a0907;

  & > div {
    width: 50%;
    height: calc(100vh - 80px);
    /* min-height: 95vh; */
  }

  & > div:first-child {
    overflow: visible;
  }

  @media (max-width: 1250px) {
    flex-direction: column;
    & > div {
      width: 100%;
    }
  }
`;

export default Chat;
