import Head from "next/head";
import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import WrapperModal from "@/componets/common/wrappers/WrapperModal";
import FreeOfferBlock from "@/componets/paywall/FreeOfferBlock";
import ProOfferBlock from "@/componets/paywall/ProOfferBlock";
import styled from "styled-components";
import StaticIndividuals from "@/componets/paywall/elements/StaticIndividuals";
import WrapperBackground from "@/componets/common/wrappers/WrapperBakground";
import HeaderModal from "@/componets/common/headerModal/HeaderModal";
import TitleMedium from "@/componets/common/title/TitleMedium";
import { useAppDispatch, useAppSelector } from "@/hooks/reducers.hook";
import { useRouter } from "next/router";
import { APP_ROUTES, StorageCellEnum } from "@/constants/common";
import SoulsIntro from "@/componets/common/soulsIntro/SoulsIntro";
import { useEffect } from "react";
import { userSlice } from "@/store/reducers/userSlice";
import { ILocalStorageData } from "../../../types/common.types";

const Paywall: React.FC = () => {
  const { readAbout } = useAppSelector((store) => store.userReducer);
  const { questionsAmount } = useAppSelector((store) => store.userReducer);
  const router = useRouter();
  const { signin } = userSlice.actions;
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (!questionsAmount) {
      alert("Notice: you have used up all available questions!");
    }

    let localData = localStorage.getItem(StorageCellEnum.USER);
    if (localData) {
      const parsedData: ILocalStorageData = JSON.parse(localData);
      dispatch(
        signin({
          id: parsedData.id,
          email: parsedData.email,
          name: parsedData.name!,
          phone: parsedData.phone!,
          nextPayment: parsedData.nextpayment as string,
          questionsAmount: parsedData.questionsamount,
          readAbout: parsedData.readabout,
          shareLink: !!parsedData.shareLink,
        })
      );
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperCentring minHeight={900}>
        <HeaderModal />
        <WrapperContent>
          <TitleMedium
            label={"Unlock full features"}
            description={
              "Share or subscribe to continue asking unlimited questions"
            }
          />
          <ModalsContainer>
            <WrapperModal
              width={"514"}
              noBorder={true}
              isPayment={true}
              isPaddingSmall={true}
              minHeight={236}
              maxHeight={421}
            >
              <FreeOfferBlock />
            </WrapperModal>
            <WrapperModal
              width={"320"}
              isPayment={true}
              isPaddingSmall={true}
              minHeight={315}
              maxHeight={421}
            >
              <ProOfferBlock />
            </WrapperModal>
          </ModalsContainer>
        </WrapperContent>
        <SoulsIntro />
        <StaticIndividuals />
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

const WrapperContent = styled.div`
  /* width: 100%; */
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;

  @media (max-width: 870px) {
    width: 343px;
    justify-content: flex-start;

    & > div:first-child {
      margin-bottom: 16px;
    }
  }
`;

const ModalsContainer = styled.div`
  width: 866px;
  height: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;

  @media (max-width: 870px) {
    flex-direction: column;
    align-items: center;
    width: 343px;
    height: 567px;

    & > div:first-child {
      margin-bottom: 16px;
    }
  }
`;

export default Paywall;
