export const GREETING_USER_QUESTIONS = [
  {
    id: 1,
    text: "What did you want to be when you grew up?",
    questionType: "qOne",
  },
  {
    id: 2,
    text: "What is the meaning of life?",
    questionType: "qTwo",
  },
  {
    id: 3,
    text: "What is your greatest accomplishment?",
    questionType: "qThree",
  },
];

export const SOULS_DATA = [
  {
    id: 2,
    name: "dr. martin luther king jr.",
    about: "political activist",
    image: "/images/souls/2_martin_luther_king.png",
    background: "/images/backgrounds/1_darkblue.png",
    placeholder: "/images/placeholders/2_martin_luther_king_placeholder.png",
  },

  {
    id: 1,
    name: "Steve Jobs",
    about: "Apple Founder",
    image: "/images/souls/1_steve_jobs.png",
    background: "/images/backgrounds/2_palegreen.png",
    placeholder: "/images/placeholders/1_steve_jobs_placeholder.png",
  },
  {
    id: 3,
    name: "elon musk",
    about: "space nerd",
    image: "/images/souls/3_elon_mask.png",
    background: "/images/backgrounds/3_violet.png",
    placeholder: "/images/placeholders/3_elon_mask_placeholder.png",
  },
  {
    id: 4,
    name: "albert einstein",
    about: "genius",
    image: "/images/souls/4_albert_einstein.png",
    background: "/images/backgrounds/4_blue.png",
    placeholder: "/images/placeholders/4_albert_einstein_placeholder.png",
  },
  {
    id: 5,
    name: "mother teresa",
    about: "philanthropist",
    image: "/images/souls/5_mother_teresa.png",
    background: "/images/backgrounds/5_yellow.png",
    placeholder: "/images/placeholders/5_mother_teresa_placeholder.png",
  },
  {
    id: 6,
    name: "jesus christ",
    about: "lord & savior",
    image: "/images/souls/6_jesus_christ.png",
    background: "/images/backgrounds/6_color.png",
    placeholder: "/images/placeholders/6_jesus_christ_placeholder.png",
  },
  {
    id: 7,
    name: "leonardo da vinci",
    about: "artist",
    image: "/images/souls/7_leonardo_da_vinci.png",
    background: "/images/backgrounds/7_green.png",
    placeholder: "/images/placeholders/7_leonardo_da_vinci_placeholder.png",
  },
  {
    id: 8,
    name: "queen elizabeth",
    about: "queen of england",
    image: "/images/souls/8_queen_elizabeth.png",
    background: "/images/backgrounds/8_someblue.png",
    placeholder: "/images/placeholders/8_queen_elizabeth_placeholder.png",
  },
  {
    id: 9,
    name: "william shakespeare",
    about: "author",
    image: "/images/souls/9_william_shakespeare.png",
    background: "/images/backgrounds/9_green.png",
    placeholder: "/images/placeholders/9_william_shakespeare_placeholder.png",
  },
  {
    id: 10,
    name: "nelson mandela",
    about: "philanthropist",
    image: "/images/souls/10_nelson_mandela.png",
    background: "/images/backgrounds/10_orange.png",
    placeholder: "/images/placeholders/10_nelson_mandela_placeholder.png",
  },
  {
    id: 11,
    name: "betsy ross",
    about: "american history",
    image: "/images/souls/11_betsy_ross.png",
    background: "/images/backgrounds/11_pink.png",
    placeholder: "/images/placeholders/11_betsy_ross_placeholder.png",
  },
  {
    id: 12,
    name: "gandhi",
    about: "philanthropist",
    image: "/images/souls/12_gandhi.png",
    background: "/images/backgrounds/12_green.png",
    placeholder: "/images/placeholders/12_gandhi_placeholder.png",
  },
  {
    id: 13,
    name: "abraham lincoln",
    about: "american president",
    image: "/images/souls/13_abraham_lincoln.png",
    background: "/images/backgrounds/2_palegreen.png",
    placeholder: "/images/placeholders/13_abraham_lincoln_placeholder.png",
  },
  {
    id: 14,
    name: "ron swanson",
    about: "tv goofy guy",
    image: "/images/souls/14_ron_swonson.png",
    background: "/images/backgrounds/14_lightblue.png",
    placeholder: "/images/placeholders/14_ron_swonson_placeholder.png",
  },
];
