export const GREETING_USER_QUESTIONS = [
  "What did you want to be when you grew up?",
  "What is the meaning of life?",
  "What is your greatest accomplishment?",
];

export const INDIVIDUALS_DATA = [
  {
    id: 1,
    name: "dr. martin luther king jr.",
    about: "political activist",
    image: "/images/individuals/2_martin_luther_king.png",
    background: "/images/backgrounds/1_darkblue.png",
  },

  {
    id: 2,
    name: "Steve Jobs",
    about: "Apple Computer Founder",
    image: "/images/individuals/1_steve_jobs.png",
    background: "/images/backgrounds/2_palegreen.png",
  },
  {
    id: 3,
    name: "elon musk",
    about: "space nerd",
    image: "/images/individuals/3_elon_mask.png",
    background: "/images/backgrounds/3_violet.png",
  },
  {
    id: 4,
    name: "albert einstein",
    about: "genius",
    image: "/images/individuals/4_albert_einstein.png",
    background: "/images/backgrounds/4_blue.png",
  },
  {
    id: 5,
    name: "mother teresa",
    about: "philanthropist",
    image: "/images/individuals/5_mother_teresa.png",
    background: "/images/backgrounds/5_yellow.png",
  },
  {
    id: 6,
    name: "jesus christ",
    about: "lord & savior",
    image: "/images/individuals/6_jesus_christ.png",
    background: "/images/backgrounds/6_color.png",
  },
  {
    id: 7,
    name: "leonardo da vinci",
    about: "artist",
    image: "/images/individuals/7_leonardo_da_vinci.png",
    background: "/images/backgrounds/7_green.png",
  },
  {
    id: 8,
    name: "queen elizabeth",
    about: "queen of england",
    image: "/images/individuals/8_queen_elizabeth.png",
    background: "/images/backgrounds/8_someblue.png",
  },
  {
    id: 9,
    name: "william shakespeare",
    about: "author",
    image: "/images/individuals/9_william_shakespeare.png",
    background: "/images/backgrounds/9_green.png",
  },
  {
    id: 10,
    name: "nelson mandela",
    about: "philanthropist",
    image: "/images/individuals/10_nelson_mandela.png",
    background: "/images/backgrounds/10_orange.png",
  },
  {
    id: 11,
    name: "betsy ross",
    about: "american history",
    image: "/images/individuals/11_betsy_ross.png",
    background: "/images/backgrounds/11_pink.png",
  },
  {
    id: 12,
    name: "gandhi",
    about: "philanthropist",
    image: "/images/individuals/12_gandhi.png",
    background: "/images/backgrounds/12_green.png",
  },
  {
    id: 13,
    name: "abraham lincoln",
    about: "american president",
    image: "/images/individuals/13_abraham_lincoln.png",
    background: "/images/backgrounds/2_palegreen.png",
  },
  {
    id: 14,
    name: "ron swanson",
    about: "tv goofy guy",
    image: "/images/individuals/14_ron_swonson.png",
    background: "/images/backgrounds/14_lightblue.png",
  },
];
