export const ABOUT_TEXT =
  "All of the characters here are not real. Everything you see and hear is entirely generated by Artificial Intelligence machines. The opinions and beliefs expressed do not represent anyone. They are hallucinations of a bunch of 1s and 0s inside of a magic computer.";
export const ABOUT_TEXT_SECOND =
  "The creators of this platform have the best intentions with this project, and deeply admire each and every character on the site. You might even say they are our Heroes. In fact, you can say that.";
export const SHARE_LINK_MESSAGE =
  "Do you have questions but don't know who to ask? What would famous people say? Visit the front-eternal.vercel.app to use EternalAI and find out the answer.";
