import PrimarySubmitBtn from "../common/buttons/PrimarySubmitBtn";
import HeaderModal from "../common/headerModal/HeaderModal";
import Checkbox from "@/componets/about/Checkbox";
import { ABOUT_TEXT } from "@/constants/modals";
import WrapperBackground from "@/wrappers/WrapperBakground";
import WrapperCentring from "@/wrappers/WrapperCentring";
import WrapperModal from "@/wrappers/WrapperModal";
import Head from "next/head";
import React from "react";

const SignIn: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal
          width={"721"}
          header={"About the platform"}
          text={ABOUT_TEXT}
        >
          <Checkbox label={"I have read the above statement"} />
          <PrimarySubmitBtn label={"continue"} />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignIn;
