import Head from "next/head";
import Header from "../common/header/Header";
import ChatContainer from "@/componets/ChatContainer";
import { useState } from "react";
import MenuModal from "../common/modals/menuModal/MenuModal";
import SoulsModal from "../common/modals/soulModal/SoulsModal";

const Chat: React.FC = () => {
  const [showModalMenu, toggleModalMenu] = useState(false);
  const [isModalSoulsOpen, toggleModalSouls] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isMenuOpen={showModalMenu} showModalMenu={toggleModalMenu} />
      <ChatContainer
        isSoulsModalOpen={isModalSoulsOpen}
        toggleSoulsModal={toggleModalSouls}
      />
      <MenuModal
        isModalMenuOpen={showModalMenu}
        toggleModalMenu={toggleModalMenu}
      />
      <SoulsModal
        isSoulsModalOpen={isModalSoulsOpen}
        toggleSoulsModal={toggleModalSouls}
      />
    </>
  );
};

export default Chat;
