import Footer from "../common/footer/Footer";
import Header from "../common/header/Header";
import HeaderModal from "../common/headerModal/HeaderModal";
import MenuModal from "../common/modals/menuModal/MenuModal";
import BackgroundDetails from "@/componets/details/BackgroundDetails";
import DetailsForm from "@/componets/details/DetailsForm";
import UpdatePaymentBlock from "@/componets/details/UpdatePaymentBlock";
import WrapperCentring from "@/wrappers/WrapperCentring";
import WrapperModal from "@/wrappers/WrapperModal";
import Head from "next/head";
import React, { useState } from "react";
import styled from "styled-components";

const Details: React.FC = () => {
  const [showModalMenu, toggleModalMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        {/* <MenuModal
          isModalMenuOpen={showModalMenu}
          toggleModalMenu={toggleModalMenu}
        /> */}
        <StyledHeaderContainer>
          <Header showModalMenu={toggleModalMenu} isMenuOpen={showModalMenu} />
        </StyledHeaderContainer>
        <StyledModalWrapper>
          <WrapperModal width={"760"} header={"Account Details"}>
            <DetailsForm />
          </WrapperModal>
          <WrapperModal width={"760"} header={"Account Details"}>
            <UpdatePaymentBlock />
          </WrapperModal>
        </StyledModalWrapper>

        <StyledFooterContainer>
          <Footer />
        </StyledFooterContainer>
        <BackgroundDetails />
      </WrapperCentring>
    </>
  );
};

const StyledHeaderContainer = styled.div`
  position: absolute;
  top: 0px;
  width: 100%;
`;

const StyledFooterContainer = styled.div`
  position: absolute;
  bottom: 0px;
  width: 100%;
`;

const StyledModalWrapper = styled.div`
  margin-bottom: 5.69vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  & > div:last-child {
    margin-top: 24px;
  }
`;

export default Details;
