import Footer from "../common/footer/Footer";
import MenuModal from "../common/modals/menuModal/MenuModal";
import Greeting from "@/componets/home/greeting/Greeting";
import Individuals from "@/componets/home/individuals/Individuals";
import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";
import { ISoulInfo } from "@/api/souls-service-types";
import client from "@/api/apollo-client";
import { ISoulsResponse } from "@/api/souls-service-types";
import { gql } from "@apollo/client";
import soulsQuery from "@/api/souls-query";
import { InferGetServerSidePropsType } from "next/types";

export async function getServerSideProps() {
  const { data } = await client.query<ISoulsResponse>({
    query: soulsQuery.getAllSouls,
  });
  console.log(data, "ssr");

  return {
    props: {
      allSoulsData: data,
    },
  };
}

export default function Home({
  allSoulsData,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const [showModalMenu, toggleModalMenu] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledBackground>
        <MenuModal
          isModalMenuOpen={showModalMenu}
          toggleModalMenu={toggleModalMenu}
        />
        <Greeting isMenuOpen={showModalMenu} modalHendler={toggleModalMenu} />
        <Individuals individualsData={allSoulsData} />
        <Footer />
      </StyledBackground>
    </>
  );
}

const StyledBackground = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow-x: hidden;
  background-color: #111115;
  z-index: -3;
`;
