import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import Head from "next/head";
import React from "react";
import styled from "styled-components";
import Image from "next/image";
import loaderImage from "@images/loader.webp";
import logoIcon from "@icons/logo.svg";

const Loader: React.FC = () => {
  let loaderWidth = 0;
  let loaderHeight = 0;
  let logoWidth = 0;
  let logoHeight = 0;
  if (typeof window !== "undefined") {
    loaderWidth = (document.documentElement.clientWidth * 17) / 100;
    loaderHeight = (document.documentElement.clientHeight * 25.75) / 100;
    logoWidth = (document.documentElement.clientWidth * 31.07) / 100;
    logoHeight = (document.documentElement.clientHeight * 2.71) / 100;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperCentring>
        <StyledLoaderBackground>
          <StyledContentWrapper>
            <Image
              alt="loader.webp"
              src={loaderImage}
              width={loaderWidth}
              height={loaderHeight}
              // quality={100}
            />
            <Image
              alt="logo.svg"
              src={logoIcon}
              width={logoWidth}
              height={logoHeight}
              // quality={100}
            />
          </StyledContentWrapper>
        </StyledLoaderBackground>
      </WrapperCentring>
    </>
  );
};

const StyledLoaderBackground = styled.div`
  position: fixed;
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  z-index: -2;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  background-color: #010100;
`;

const StyledContentWrapper = styled.div`
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  img:first-child {
    margin-bottom: 54.77px;
  }
`;

export default Loader;
