import TextBtn from "@/componets/common/buttons/TextBtn";
import Header from "@/componets/common/header/Header";
import PrimaryMenuBtn from "@/componets/common/modals/menuModal/menuButtons/PrimaryMenuBtn";
import TextMenuBtn from "@/componets/common/modals/menuModal/menuButtons/TextMenuBtn";
import { MENU_LINKS, SOCIAL_LINKS } from "@/constants/modals";
import Head from "next/head";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import styled from "styled-components";
import facebookIcon from "@icons/modal-social-facebook.svg";
import instagramIcon from "@icons/modal-social-instagram.svg";
import twitterIcon from "@icons/modal-social-twitter.svg";
import discordIcon from "@icons/modal-social-discord.svg";
import backgroundMenuImage from "@images/background-menu.png";
import localStorageHandler from "@/utils/local-storage-hendler";
import { APP_ROUTES } from "@/constants/common";

const Menu: React.FC = () => {
  const isAuth = localStorageHandler.getAccessToken();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledSectionWrapper>
        <Header haveClose={true} />
        <StyledMenuWrapper>
          <StyledMenu>
            {MENU_LINKS.map((item, index) => (
              <Link key={index} href={item.link}>
                {item.label}
              </Link>
            ))}
          </StyledMenu>
          <StyledSocialContainer>
            <div>
              <Link href={SOCIAL_LINKS.Facebook}>
                <Image
                  src={facebookIcon}
                  alt="modal-social-facebook.svg"
                  width={24}
                  height={24}
                />
              </Link>
              <Link href={SOCIAL_LINKS.Instagram}>
                <Image
                  src={instagramIcon}
                  alt="modal-social-instagram.svg"
                  width={24}
                  height={24}
                />
              </Link>
              <Link href={SOCIAL_LINKS.Twitter}>
                <Image
                  src={twitterIcon}
                  alt="modal-social-twitter.svg"
                  width={24}
                  height={24}
                />
              </Link>
              <Link href={SOCIAL_LINKS.Discord}>
                <Image
                  src={discordIcon}
                  alt="modal-social-discroed.svg"
                  width={24}
                  height={24}
                />
              </Link>
            </div>
          </StyledSocialContainer>
          {document.documentElement.clientWidth < 871 ? (
            <StyledButtonsContainer>
              {isAuth ? (
                <TextBtn label={"sign out"} />
              ) : (
                <>
                  <Link href={APP_ROUTES.Signup}>
                    <PrimaryMenuBtn />
                  </Link>

                  <Link href={APP_ROUTES.Signin}>
                    <TextMenuBtn label={"login"} />
                  </Link>
                </>
              )}
            </StyledButtonsContainer>
          ) : (
            <></>
          )}
        </StyledMenuWrapper>
        <StyledBackgroundMenu>
          <Image
            alt="background-menu.png"
            src={backgroundMenuImage}
            fill={true}
            style={{ objectFit: "cover", backdropFilter: "blur(107px)" }}
            quality={100}
          />
        </StyledBackgroundMenu>
      </StyledSectionWrapper>
    </>
  );
};

const StyledMenuWrapper = styled.div`
  margin-top: 20vh;
  width: 100%;
  height: auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  z-index: 2;
`;

const StyledMenu = styled.div`
  margin-top: 30px;
  width: 279px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  list-style-type: none;
  border-bottom: 2px solid #2f2535;
  z-index: 2;

  & > a {
    width: 100%;
    margin-bottom: 32px;
    text-align: center;
    font-family: "Avenir Medium";
    font-weight: 500;
    font-size: 32px;
    line-height: 48px;
    letter-spacing: -0.01em;
    color: white;
    background-color: transparent;
  }

  & > a:hover {
    color: ${({ theme }) => theme.color.pink};
  }
`;

const StyledSocialContainer = styled.div`
  margin-top: 32px;
  width: 279px;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  z-index: 2;

  & > div {
    width: 155.11px;
    height: 24px;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;

    img:hover {
      cursor: pointer;
    }
  }
`;

const StyledButtonsContainer = styled.div`
  width: 343px;
  height: 84px;
  padding: 0px 16px;
  position: absolute;
  bottom: 32px;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  align-items: center;
  z-index: 2;
  a {
    width: 343px;
  }

  & > a:last-child {
    margin-top: 24px;
  }
`;

const StyledSectionWrapper = styled.section`
  width: 100%;
  max-width: 1640px;
  margin: 0 auto;
  height: 100%;
  min-height: 100%;
  background-color: #0a0907;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  overflow: hidden;
`;

const StyledBackgroundMenu = styled.div`
  position: fixed;
  top: 0px;
  left: 0px;
  height: 100%;
  width: 100%;
  overflow: hidden;
  z-index: 1;
`;

export default Menu;
