import WrapperCentring from "@/componets/common/wrappers/WrapperCentring";
import { InferGetServerSidePropsType } from "next";
import Image from "next/image";

import Head from "next/head";
import React from "react";
import { ISoulInfo } from "@/api/souls-service-types";
import client from "@/api/apollo-client";
import { ISoulsResponse } from "@/api/souls-service-types";
import { gql } from "@apollo/client";
import soulsQuery from "@/api/souls-query";

import PicWebP from "../../public/images/picture-compare/Picture-with-fon.webp";
import PicTinyPng from "../../public/images/picture-compare/Picture-with-fon-tiny.png";
import PicPng from "../../public/images/picture-compare/Picture-with-fon.png";
import styled from "styled-components";

function Sample() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperCentring>
        <StyledBtn>Btn</StyledBtn>
      </WrapperCentring>
    </>
  );
}

const StyledBtn = styled.button`
  background-color: green;
  border: 10px solid;
  border-left-width: 3px;
  border-image: ${({ theme }) => theme.backgroundColorGradient};
`;

export default Sample;
