import HeaderModal from "../common/headerModal/HeaderModal";
import StartedForm from "@/componets/signup/StartedForm";
import WrapperBackground from "@/componets/signup/WrapperBakground";
import WrapperCentring from "@/wrappers/WrapperCentring";
import WrapperModal from "@/wrappers/WrapperModal";
import Head from "next/head";
import React from "react";

const SignUp: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <WrapperModal
          width={"721"}
          header={"Get started"}
          text={"To continue please create an account"}
        >
          <StartedForm />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignUp;
