import AdditionalFormInfo from "../common/additionalFormInfo/AdditionalFormInfo";
import HeaderModal from "../common/headerModal/HeaderModal";
import SiignInForm from "@/componets/signin/SignInForm";
import WrapperBackground from "@/wrappers/WrapperBakground";
import WrapperCentring from "@/wrappers/WrapperCentring";
import WrapperModal from "@/wrappers/WrapperModal";
import Head from "next/head";
import React from "react";

const SignIn: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapperCentring>
        <HeaderModal />
        <HeaderModal />
        <WrapperModal width={"721"} header={"Login"}>
          <SiignInForm />

          <AdditionalFormInfo
            label="Don’t have an account?"
            labelLink="Sign up"
            wayLink="/signup"
          />
        </WrapperModal>
        <WrapperBackground />
      </WrapperCentring>
    </>
  );
};

export default SignIn;
